# =============================================================================
# FILE: database/migrations/script.py.mako
# DESCRIPTION: Alembic migration script template
# LOCATION: database/migrations/script.py.mako
# PURPOSE: Template used to generate new migration files
# =============================================================================

"""Add gender and shammas_rank to users

Revision ID: 258748603213
Revises: b6791066a1ed
Create Date: 2025-11-24 08:26:02.663744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258748603213'
down_revision = 'b6791066a1ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('shammas_rank', sa.String(length=20), nullable=True))
    op.create_index('idx_users_gender', 'users', ['gender'], unique=False)
    op.create_index('idx_users_shammas', 'users', ['shammas_rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_shammas', table_name='users')
    op.drop_index('idx_users_gender', table_name='users')
    op.drop_column('users', 'shammas_rank')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
