# =============================================================================
# FILE: database/migrations/script.py.mako
# DESCRIPTION: Alembic migration script template
# LOCATION: database/migrations/script.py.mako
# PURPOSE: Template used to generate new migration files
# =============================================================================

"""Initial migration

Revision ID: b6791066a1ed
Revises: 
Create Date: 2025-10-23 20:48:32.413436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6791066a1ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
